### ISSUE TITLE
SlugRelatedField and _links

### ISSUE THREAD

**Issue by claytondaley** [Artory/drf-hal-json#25] opened 2017-08-11 00:41 UTC
`SlugRelatedField` is getting put into the `_links` section even if it's not a URI (let alone a valid one).

I'm using the `SlugRelatedField` to extract the name of a Django group.  I need the group name to tell a user who's responsible for a task (if that user is not).  The groups are not available over REST so it doesn't make sense to represent them as a linkable resource.  As far as REST is concerned, the slug is just an attribute of the object.

While `SlugRelatedField` could be used to pick a URI off an object, this behavior is not the appropriate default.  Instead, I believe this feature should require a dedicated class asserting that it's representing a `UriSlugRelatedField`.

**Comment by claytondaley** [comment] 2017-08-11 00:43
If there isn't another way to indicate that these classes are not links, the obvious place to fix the issue is [here](https://github.com/Artory/drf-hal-json/blob/master/drf_hal_json/serializers.py#L81).  `SlugRelatedField` is a `RelatedField`, but not all `RelatedField`s are necessarily linkable URIs.

**Comment by claytondaley** [comment] 2017-08-11 01:00
If you agree in principle, I need some guidance before I can submit a PR.  I'm not clear which fields can/should be completely removed from the check, which fields (e.g. `HalHyperlinkedRelatedField` and `HalHyperlinkedIdentityField`) need to be included once their ancestors are removed, and which need new `Hal`-derived variants.

I suspect this change won't need new tests because the existing tests for non-`Hal`-derived objects can simply be converted to cover the new `Hal`-derived ones.

**Comment by webjunkie** [comment] 2017-08-14 13:24
Duplicate of #22

**Comment by webjunkie** [comment] 2017-08-14 13:26
@claytondaley What could help is if you might update the test cases and provide one that fails for this issue here.

**Closed** 2017-08-14 14:04 UTC
